z-song/laravel-admin

- src/Form/Field/File.php
比如配置adminj.upload.host为/upload，最后渲染成为upload/balabala，成为相对路径
> 配置使用绝对路径时，使用trim后得到的是相对路径，无法得到正确的路径，故改为rtrim

- migrations/2016_01_04_173148_create_admin_tables.php
问题来源：在应用input值过大的时候无法更新记录到日志操作表，导致数据不能提交。
> 更新初始操作记录表的input内容字段类型

- src/Form/Field/Number.php
The default value for the number field gets ignored
```php
$form->number('quantity')->default(1); // still shows 0
```
> number field does not longer ignore default value when rendering

- src/Form/Field/SwitchField.php
Current code doesn't use the checkbox default value if empty
```php
$form->switch('a_boolean_field')->default(1);
```
> switch field needs to use the ‘default’ value if value is empty

- src/Auth/Database/Menu.php
Fixes https://github.com/z-song/laravel-admin/issues/161
There are likely other places that need to use Grammar to quote identifiers. I'll update this PR as I learn the laravel-admin framework.
> Use grammar to quote identifier

- src/Form/NestedForm.php
Fields in a nested form don’t store values that are considered empty by PHP’s ‘empty’ function. Use is_null instead as used in the ‘prepare’ method inside Form
> add ability to save e.g. ‘0’ to fields in a nested form

- src/Form/Field.php
if you input something like ‘this is a “test” with quotes’ it stores the value correctly, but next refresh will only show ‘this is a ‘
> input attribute values need to be escaped

- views/filter/select.blade.php
If you create a filter in the grid with these options:
```php
$filter->equal('is_paid')->select(['0' => 'no', '1' => 'yes']);
```
'no' is selected by default even if no filter is applied.
> fix incorrect selected value in grid filter when options are [0=>’off’, 1=>’on’]

- src/Form/Field/HasMany.php
- views/form/hasmanytab.blade.php
更改HasMany tab 模式的按钮位置，使当内容为空的时候，更符合习惯位置。
> change HasMany tab mode's button position

- src/Form/NestedForm.php
new rows get original data from previous defined rows leading to weird behaviour
if the hasMany component already has e.g.. 3 existing rows and you add a new one, the new row’s original data gets filled in with the last defined original data
fixes #341 again
> HasMany: new rows get original data from previous defined rows

- src/Middleware/BootstrapMiddleware.php
If you use Form::extend or Form::forget in bootstrap.php it’s assets were not required/forgotten
I for example don't use the map field, yet still its resources got loaded
another custom field didn't get its assets
> bootstrap.php needs to be called before Form::collectFieldAssets()

- src/Admin.php
Using `$router->resources()` you can't specify `options`. So using `$router->resource()` instead and removed routes which doesn't have any methods.
> Removed few dead end routes.

- src/Grid/Displayers/Editable.php
当editable的column带 ```.``` 的时候，会出现错误。
> fix Editable class

- src/Grid.php
if the column is a relation, there is no need to check if it’s a column in the database
this way we don’t need a query if the column is a mutator or relation
eg
```
$grid->pack_products(); // this is a HasMany relation
```
Currently it checks first if 'pack_products' is a column, but it should check first if it's a mutation or a relation. This way we skip the redundant call to the database.
BTW
if i use `$grid->column('pack_products');` the model doesn't use the `->with('pack_products')` for some reason.
> swap the order for creating columns through the magic method

- src/Form/Field.php
Calling $field->addElementClass('someClass') throws an error because $this->elementClass is not an array by default, so the merge fails
> Field->elementClass needs to be an array

- src/Grid.php
Currently the grid queries the database for a list of schema columns for each column defined in the grid. This change queries the list of columns once when the grid is created, and then checks that list for valid columns. This is faster and uses fewer queries for each grid setup.
This is a cleaner and more current version of a previous pull request
> Cache the table columns for later use when grid is created

- src/Admin.php
This isn't really a laravel-admin problem, but it fixes a bug in the way laravel-ide-helper incorrectly identifies the class returned by a method, if the class isn't fully qualified in the method docblock. This causes PHPStorm to complain very loudly. 
Fully qualifying the class returned by these methods has no other side effects.
> ide-helper grabs the wrong namespace when it’s not fully qualified

- src/Form/Builder.php
- src/Form/Tools.php
- views/form.blade.php
A few small model-form errors:
1. When the form->resource is something like ```http://example.com/resources/151/edit``` the 'List' button shows a 'list' link of ```http://example.com/resources/151``` instead of the correct ```http://example.com/resources```. This request fixes that by letting the form builder's getResource method accept a 'slice' argument, and altering the slice requested by the List button if '/edit' is in the url.
2. When the form is in the undocumented 'view' mode, which displays the form but removes the 'Submit' button, or the Submit button is disabled, the form still contains a valid csrf_token meaning it could still be submitted manually. This request removes the csrf_token when there is no Submit button.
> Model form fix

- src/Form/Field/Checkbox.php
- views/form/checkbox.blade.php
Stacked checkboxes make it easier to draw a tree menu for example
In my example, the options get indented with `&nbsp;` to create a tree like menu.
`$form->checkbox('categories')->options(...)->stacked();`
> option to draw checkboxes inline (default) or stacked

- src/Providers/AdminServiceProvider.php
现在是固定使用 `Encore\Admin\Auth\Database\Administrator`, 
但是如果我自定义了一个模型继承了它并扩展了功能, 
而且已经在在 `config/admin.php` 里自定义了 `database.users_model`,
这时候通过 `Admin::user()` 获取到的依旧是原来的 `Encore\Admin\Auth\Database\Administrator`.
> 修改在注册guard时使用的模型

- src/Grid/Filter.php
- src/Grid/Filter/Ilike.php
- views/filter/ilike.blade.php
In PostgreSQL you can run this: `WHERE name ILIKE '%john%'` for case-INsesitive LIKE. This pull request adds it:
```php
$grid->filter(function (Filter $filter) {
$filter->ilike('contact.name');
});
```
> Ilike filter for postgreSQL

- tests/TestCase.php
On Mac if you try to run tests - they will fail, because tests try to connect to `localhost` and on Mac for some reason you get: `PDOException: SQLSTATE[HY000] [2002] No such file or directory`
Stackoverflow suggests changing it to `127.0.0.1` - that works: http://stackoverflow.com/a/22927341/37141 
So, this pull request allows me to run tests as `MYSQL_HOST=127.0.0.1 vendor/bin/phpunit` (otherwise tests don't run at all) and it doesn't change anything for already existing code.
> Allow to redefine mysql host

- src/Form/Field/Tags.php
Form去掉formatValueBeforeSave逻辑之后, 在表单提交时 tags的数据在insert和update的时候都会使用直接array , 触发 Array to string conversion错误.
此处将原来的formatValueBeforeSave方法的逻辑加入tags的默认prepare中
> fix form tags submit error

- src/Form.php
Sometimes I want to access form data of ignored fields in callback functions. It is not possible at this moment because the `saving` & `saved` callbacks are called after the ignore fields are filtered. 
I add a `submitted` callback in this pull request so that we can access the raw data of the ignored fields before they are filtered.
> Add submitted callback.

- src/Form/Field/File.php
- src/Form/Field/SwitchField.php
- views/form/switchfield.blade.php
#719 #
具体问题请见我提出的issue
目前仅对 file.php 和 switchField.php 做了修改。
希望采纳
> 修复表单中一对多字段jquery选择器混乱问题，方法为在原有class选择器之外，加上name选择。以此来避免重复

- src/Tree.php
Sometimes I need to access the items of the tree for further processing, for example for exporting to json, xml.
This pull request add `getItems()` function to access the tree's items from outside.
> Add getItems() to access the tree’s items.

- src/Tree.php
- src/Tree/Tools.php
- views/tree.blade.php
ModelTree doesn't have ability to add custom tools like ModelForm & ModelGrid at this moment. This pull request adds this ability. You can then add a custom button using codes like the following.
````
public function index()
{
return Admin::content(function (Content $content) {
$content->header('Categories');
$content->body(Category::tree(function($tree) {
$tree->tools(function($tools) {
$tools->add('<a class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>&nbsp;&nbsp;Export JSON</a>');
});
}));
});
}
````
> Add ability to add custom tools for ModelTree.

- src/Grid/Filter/Where.php
I'd like to filter on specific values within a json column.
The column contains translations and I wan't to create af filter per suppported locale.
Content of the column
```
{
"en": "Howdy!",
"fr": "Bonjour",
"nl": "Hallo"
}
```
filter code (simplified):
Since the closure is in a loop, the queryHash (based on location of the Closure) is the same for all filters. Adding the label makes is unique and solves the problem.
```php
// JSON case insensitive search
foreach (config('test.available_locales', []) as $locale => $info) {
$filter->where(
function (Builder $query) use ($locale) {
$query->whereRaw(
'`value`->\'$.'.$locale.'\' COLLATE utf8mb4_unicode_ci like ?',
['%'.$this->input.'%']
);
},
'Value ('.$locale.')'
);
}
```
> make Where queryHash uniquer

- src/Form/Tools.php
It looks at line 52 'event' must be specified as function parameter in order to work the preventDefault .
> Model-form Back button not working in Firefox

- src/Form/Field/Select.php
allowClear option is not enough and throws error if user click the x to clear the select value.
Additional option is needed to work as expected: placeholder.
> Fix select field when Clear is requested

- views/index.blade.php
tell the browser what language we're using. 
Some content might be in another language and this sometimes triggers the auto-translate option in Chrome.
> add lang attribute to <html> tag

- src/Auth/Database/AdminPermission.php
use the built-in laravel caching for roles and permissions instead of using a query all the time
#881
> check permissions/roles query optimisation

- composer.json
- src/Grid/Filter.php
You can only enable it using 'useModal()' so it should be off by default
> turn filter modal off by default

- src/Grid/Displayers/Image.php
修复Grid的image方法在显示的时候没有用到自定义的server名字
> fix grid image not use server url

- src/Controllers/AuthController.php
- 'list' button returns a 404 since there is no overview of users
- back button only works if you haven't submitted the form
so hiding them is better imo
> hide back/list buttons on user settings page

- src/Middleware/LogOperation.php
```
'except' => [
'admin/auth/logs*',
'get:admin/*',
],
```
$method does not exist as variable and is therefor always empty
When trying to not log all GET operations, nothing got logged
> fix incorrect log operation

- src/Grid/Filter/Presenter/Select.php
修复使用`$filter->equal('column')->select('api/users');`时，jquery选择器无法正确选择对应元素的问题。
> 修复查询过滤select表单类型无法从api加载数据的问题

- resources/views/partials/error.blade.php
相关的问题讨论：
https://github.com/z-song/laravel-admin/issues/1492
在laravel的errors里面增加了一个error为key的MessageBag
所以在controller中，如果我们需要自定义返回的Error(而不是Form表单的错误的时候)，我们可以使用
return Redirect::back()->withInput()->withErrors('城市已经在重跑列表中了', 'error');
这样就可以自定义控制器错误了。
貌似 在兼顾Form的Error不限制在头部，和头部的Error保持title/message结构，这个是一个兼容方案了。
> 增加对使用laravel自定义的errors的兼容

- src/Form/Field.php
在form中使用rules规则进行验证时，增加对array的支持，特定于当使用正则表达式时包含“|”符号会出bug
> fix bug for field rules of form used regex array

- src/Form/Field/File.php
rt：修复bug：修改表单时，文件组件 重新上传新文件的预览位置 无法覆盖旧文件预览
>  修复bug：修改表单时，文件组件 重新上传新文件的预览位置 无法覆盖旧文件预览

- src/Form/Field/UploadField.php
if I defined a special disk and set by disk() method, the URL for file or image in this disk must be not generated by default disk configured by 'admin.upload.disk'.
如果用disk()方法指定了disk, 当生成指向存储空间中的文件或图片的url时，就应该使用新的disk, 而不是原来配置文件中的默认配置。
> Update UploadField.php. correct url if defined special disk by disk()

- src/Form/Field/Date.php
Now date picker appears only by input click, but I think that it's a good idea to show date picker also by icon click (most of my users tried to do that).
(my suggestion https://github.com/z-song/laravel-admin/issues/1820)
> show the date picker on input and icon click

- src/Form/Field/MultipleSelect.php
When connection is defined in Model:
```php
protected $connection = 'mysql';
```
The $fullKey becomes in the format [connection].[table].[column] instead of [table].[column], 
```php
$fullKey = $relation->getQualifiedRelatedPivotKeyName(); #mysql.table1.name
```
So the following syntax is unable to get the correct column name
```php
substr($fullKey, strpos($fullKey, '.') + 1); #table1.name instead of name
```
> Fix multipleSelect otherKey bug when connection name is included in fullKey

- src/Form/Field.php
Currently, if you pass in an array of rules, they will be skipped completely and not be processed / added. 
This becomes a problem, if you need e.g. extended regexes, which contain a pipe symbol. The regular string handling will always "cut" these regexes (simple explode on the full string by pipe symbol), so working array handling is needed.
> Fix passing array of rules to field

- src/Middleware/LogOperation.php
admin_operation_log 表 path 字段长度是 255,一般情况下够用，但在批量删除时可能超出，如：
post /admin/auth/logs/58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,39,38
假如主键 id 偏大或批量删除的数据过多时便超出报错了，故应把 path 截取前 255 位作为简易的解决方式:
'path'    => substr($request->path(), 0, 255),
> LogOperation path 字段截取前255字符

- src/Form/Field.php
Upgrade  removeRule method  for able to  remove a rule by keyword.
For example,  In Form/Field/File line 73 call $this->removeRule('required');
If this field has a rule  like  below , use the old method    
required_unless|regex:/^\d+$/|min:10
old method result: _unless|regex:/^\d+$/|min:10    and will cause an error then validator make!
After upgrade : regex:/^\d+$/|min:10
From Issue: https://github.com/z-song/laravel-admin/issues/2186
> Upgrade  removeRule method  

- src/Form.php
如果form对象需要添加额外input或者set一个input的value的时候，如果使用__set设置到inputs属性上，其实最后model操作的时候没有merge上
> fix __set() invalid problem

- src/Form/Field/MultipleSelect.php
In form function, if developer adds embeds>checkbox, and something has error in form display (ex, required error other field), throw Exception.
Because in MultipleSelect.php>fill function, "current($relations)" value is null with embeds>checkbox field if user doesn't select, so "is_string(current($relations))" is false.
Then, calling else block, $this->getOtherKey() is error because almost embeds>checkbox field is no relation.
So I added checking "is_null(current($relations))". if current($relations) is null, $this->value = null.
> Bug fix MultipleSelect.

- src/Form.php
1. `Form::complete()` 方法更名为 `callSaved()`，与 `callSubmitted()`、`callSaving()` 统一命名；
2. 之前如果多次调用 `$form->saved(function() {})` 只有最后一个回调会生效，现在都会生效。
> 表单支持定义多个回调

- src/Form/Field/Html.php
Currently there is no option to get to the data in the html field component in a nested form. In a normal form you can use the '$this->model()' to get to the data, but in a nested form you get the parent model, and not the relation one
Currently in a hasMany form:
```php
$nestedForm->html(
function ($form) {
$id = $form->model()->id; // this is the parent model, not the relation one
return '<a href="link?id='.$id.'" class="btn btn-default">Do something</a>';
}
);
```
suggestion:
```php
$nestedForm->html(
function ($form, $data) {
$id = array_get($data, 'id'); // this is the id of the hasmany relation model
return '<a href="link?id='.$id.'" class="btn btn-default">Do something</a>';
}
);
```
> pass along value in callback of `Html->render()`

- src/Form/Field.php
发现很多人需要编辑表单的时候对数据格式化显示
@z-song 给出的解决是model里面加方法
`getColumnNameAttribute`
这样前台的显示也一并被格式化了。
实际情况是，前台需要显示和数据库里保存的数据一致，而编辑人员看到的是格式化之前的数据。
比如说价格，数据库保存的和前端显示的都是以元为单位(显示位置多，就可以不用一一转化，直接取数据库的值显示)，而后台人员看到的是以分为单位。
所以上面的方法就不适用了，找了下发现挺多人问同样的问题却都没有合适的解决，就改了下。
usage:
`$form->text('subhead', '副标题')->rules('required')->format(function($value) {
return str_replace('-', ' ', $value);
});`
> custom format form column data when edit

- src/Form/Field/UploadField.php
patch to fix compatibility with packages that setup storage at run time (like hyn/multi-tenant)
> Form/Field/UploadField: check for disk existence only if Exception is thrown

- resources/views/form/tags.blade.php
- resources/views/index.blade.php
- src/Form/Field/Tags.php
解决 issue #1917
原来的 Tags 不支持多对多关联，此 PR 增加了多对多关联的支持并且**兼容原来 Tags 的用法**。
`Tags` 类增加了 `pluck` 方法，比如在博客系统中，文章的标签与文章属于多对多关联的情况下，使用方法如下：
`Post`  的 `tags` 方法
```php
public function tags()
{
return $this->belongsToMany('App\Models\Tag', 'post_tag', 'post_id', 'tag_id');
}
```
`PostController` 的 `form` 方法里
```php
// 修改了 options 方法，在调用了 Tags 的 pluck 方法后，
// 如果 options 方法传入了 Collection 对象则会自动调用 Collection 的 pluck 方法，更加简洁。
$form->tags('tags', 'tags')
->pluck('name', 'id')
->options(Tag::all());
``` 
在这个示例中，HTML 结果如下：
```html
<select class="form-control tags" style="width: 100%;" name="tags[]" multiple="multiple" data-placeholder="输入 tags"  >
<option value="1" selected>php</option>
<option value="2" selected>js</option>
<option value="3" >html</option>
<option value="4" >css</option>
</select>
``` …
> Fix #1917 Tags 增加多对多关联的支持

- src/Show.php
$show->sinif('Sınıf'); // Show label as "Sinif"
After this
$show->sinif('Sınıf') // Show label as "Sınıf"
> Fix - Label support for one-to-one relations on Show

- resources/views/show/field.blade.php
- src/Show/Field.php
修复 issue #2490 
漏洞原因是因为 `field.php` 中的内容采用了 `{!! $content !!}` 输出原内容而未经转义。经过本人考量直接将全部字段内容转义不合适，因为部分内容需要HTML格式显示。所以修改了 `Field.php` 这个类，增加了 `escape` 属性，且默认值为 `true` 并且修改了模板。实现了普通字段默认转义 HTML 的功能，同时还可以通过 `setEscape` 方法设置不转义。
示例如下：
``` php
protected function detail($id)
{
$show = new Show(Post::findOrFail($id));
$show->id('Id');
// title 字段值默认被转义
$show->title('Title');
// content 字段的值不会被转义
$show->content('Content')->setEscape(false);
return $show;
}
```
> fix #2490 Show 页面XSS漏洞

- src/Form/Field/Textarea.php
I use a column as array, I can add and show data. But I can't edit. Because field casting as array. We need to convert to string.
```
protected $casts = [
'veri' => 'array'
];
```
On edit page, it's ok.
> Casts -> array support for textarea

- src/Grid/Displayers/Image.php
Last parameter for expand feature
`$grid->picture()->image('', 40, 40, true);`
Expanding uses bootstrap modal. No need extra JS or CSS file.
> Expand function for grid->image column

- src/Grid/Displayers/Checkbox.php
- src/Grid/Displayers/Editable.php
- src/Grid/Displayers/Radio.php
- src/Grid/Displayers/Select.php
修复 issue #2485 #1572
现在 `Grid` 的 `Select`、`Editable` 的 `select` 方法、`Checkbox`、`Radio` 均支持传递闭包。
使用方法如下：
``` php
$grid->created_at('Created at')->radio(function ($row) {
return [$row->created_at, $row->updated_at];
});
```
传递的闭包「接收参数」为本行数据的数组，「返回值」为真正传递的数据数组。
另外由于使用了闭包类的 `call` 方法调用闭包，所以闭包内的 `$this` 指向当前 `Displayer` 实例，可以使灵活性更高，使用示例如下：
``` php
$allTags = Tag::all()->pluck('name', 'id')->toArray();
$grid->tags('Tags')->checkbox(function () use ($allTags) {
// $this 指向 Checkbox 实例
$this->value = array_column($this->value, 'id');
return $allTags;
});
```
以上代码效果如下图
---
另外本人发现 `Checkbox` 类并没有将 `Arrayable` 类型的 `value` 转为普通数组的过程，这会导致以下代码失败。
``` php
$grid->tags('Tags')->pluck('id')->checkbox(function () {
return Tag::all()->pluck('name', 'id')->toArray();
});
``` 
出现错误：
所以本人修改了 `Checkbox` 类，增加了对 …
> fix #2485 #1572 部分 Displayer 支持传递闭包参数

- src/Grid/Filter/AbstractFilter.php
解决 issue #2541 
关闭默认 ID 过滤器后自定义新的  ID 过滤器，示例如下：
``` php
$grid->filter(function (Grid\Filter $filter) {
$filter->disableIdFilter();
$filter->equal('id', '产品序列号')->setId('product_id');
});
```
---
解析：
不能在调用 `disableIdFilter` 方法后添加「自定义 ID 过滤器」的原因是： `Filter` 类的 `removeIDFilterIfNeeded` 会将所有 `id` 为 `model` 主键名的 `filter` 都移除，又因为 `filter` 的 `id` 只能为 `column` 名而不能自定义。所以「默认 ID 过滤器」和「自定义 ID过滤器」的 `id` 都为 `model` 主键名，统统都会被移除。因此新增了 `setId` 方法，允许用户自定义 `id`。
PS：
本人也思考过能不能实现「存在自定义就用自定义ID过滤器，不存在就用默认ID过滤器」的功能。后面实现这样似乎改动比较大，可能会有不兼容的修改。所以采用这个折中的方法。当然如果有更好的方法，就更好了！
> fix #2541 Filter 支持自定义 id

- src/Grid/Displayers/SwitchDisplay.php
修复 issue #2546 
产生 BUG 的原因是 `SwitchDisplay` 的 `display` 方法中设置 CSS 类名和发送 AJAX 请求的参数均直接用了 `$this->column->getName()` 方法获取的列名，但在关联表的时候列名为 `关联方法名.字段名` 因为 `.` 号不符合 CSS 语法，导致 `switch` 无法正常使用。~~~直接将列名中的 `.` 替换为 `_` 可解决该问题。~~~
所以将列名的 `.` 替换为 `-`，设置为 CSS 类名。
此外在发送 AJAX 请求时，因为带 `.` 号的参数，会被 PHP 自动转义为 `_`，例如 `order.status` 会变为 `order_status`，导致无法正常更新对应的关联关系的值，但是将其改为 `order[status]` 即可正常更新。
使用 DEMO
``` php
protected function grid()
{
$grid = new Grid(new Post);
$states = [
'on' => ['value' => 'open', 'text' => 'OPEN', 'color' => 'primary'],
'off' => ['value' => 'close', 'text' => 'CLOSE', 'color' => 'default'],
];
$grid->order()->status('Order Status')->switch($states);
}
protected function form()
{
$form = new Form(new Post);
$states = [
'on' => ['value' => 'open', 'text' => 'OPEN', 'color' => …
```
> fix #2546 修复关联表不支持 switch 的 bug

- docs/zh/model-form-fields.md
- docs/zh/model-grid-column.md
- docs/zh/model-grid-filters.md
- src/Grid/Displayers/SwitchGroup.php
哈哈，又马大哈了，之前修复了 `Switch`的问题（#2548）却忘记修复 `Switch Group`。这个 PR 用同样的方法修复了这个问题。另外更新了一下文档，不过本人文笔不好，如果描述不清或有误请指正。
> Switch Group 支持关联表并完善文档

- src/Traits/ModelTree.php
- tests/ModelTreeTest.php
- tests/models/Tree.php
使用场景：
如我使用 ModelTree 构建一个文件系统，展示的时候是没有问题的，但是当我新建文件/文件夹的时候，我希望能选择的父级是只能是 type=文件夹的，并增加了可以修改根级别显示的文字，这不会影响到原来的代码。
> modelTree::selectOptions增加过滤功能

- src/Form/Field/Map.php
如果使用数字当参数 ```new Map(45, 116)```, 则会在Field::formatName()的第一个判断 if (is_string($column)) { 处判断失败, 会导致 Field::formatName() 无限循环.
> Field::formatName() 判断失败, 导致此函数无限循环.

- src/Show/Field.php
I used file field on form. But this isn't required so when no file selected.. Show empty file dialog.
Now will not appear.
> Don't show if file is empty

- src/Grid/Filter/Presenter/Select.php
在filter有级联select框存在时 , 会导致多次搜索过后多次请求级联API , 应增加取消绑定change事件的代码
> 修复filter的级联select框在多次搜索时 pjax 重复绑定change事件

- src/Form.php
有`newQuery`的话，一开始`$builder`就是`Illuminate\Database\Eloquent\Builder`，就算在模型里重写了`public static function with`也不被调用，应该把这个去掉，这样当用户定义`with`时，调用自定义的，没有定义时，调用默认的。
> [fix]#2743 Call custom `with` when overwrite, otherwise the default.

- src/Layout/Column.php
ex. col-sm-6 col-lg…12 col-xs-3
How to use
~~~
///// current writing
$content->row(function(Row $row) {
$row->column(4, 'foo');
$row->column(4, 'bar');
$row->column(4, 'baz');
});
// output <div class="row"><div class="col-md-4">foo</div><div class="col-md-4">bar</div><div class="col-md-4">baz</div></div>
///// supported array
$content->row(function(Row $row) {
$row->column(['md' => 4, 'sm' => 6, 'xs' => 12], 'foo');
$row->column(['md' => 4, 'sm' => 6, 'xs' => 12], 'bar');
$row->column(['md' => 4, 'sm' => 6, 'xs' => 12], 'baz');
});
// output <div class="row"><div class="col-md-4 col-sm-6 col-xs-12">foo</div><div class="col-md-4 col-sm-6 col-xs-12">bar</div><div class="col-md-4 col-sm-6 col-xs-12">baz</div></div>
~~~
*I have error StyleCI, So I updated source code
> supported bootstrap grid prefix in Layout/Column, 

- src/Widgets/Form.php
pushField function in Form is "public", but pushField function in Widgets\Form is "protected".
So we cannot call this in controller.
So I changed access level protected to public.
> Change pushField function in WidgetsForm protected to public

- src/Console/MakeCommand.php
Write your own controller stub file (eg. /path/to/my.stubs)  based on https://github.com/z-song/laravel-admin/blob/master/src/Console/stubs/controller.stub
Then specify your stub file when making controllers:
```sh
php artisan admin:make --model=MyModel --stub=/path/to/my.stubs MyController
```
> Added an option to custom the controller stub

- src/Form.php
> 修复在Form中，给字段设置空值无效

- .gitignore
- src/Controllers/PermissionController.php
当直接用域名作为入口时类似这样 http://www.admin.com
把 admin.route.prefix 配置为空字符，但是这样在权限列表里面的权限列表所有路由前面都显示两个 //
例如：
//auth/login
这个对有洁癖的人很有疗效，看着不舒服
> 修正当 admin.route.prefix 为空的时候权限列表的路由那里显示两个 / 的bug

- src/Auth/Permission.php
目前权限控制，如果 ajax 请求还是返回整个页面，前端 js 无法很好地做相应的处理。
因此调整为如果是 ajax 请求没有权限就返回 403 状态，前端根据状态码做处理
> 权限控制如果是 ajax 请求时，没有权限返回 403 Forbidden 状态

- src/Grid/Filter.php
满足更自定义化的filter，column可以不在表中
示例如下：
默认显示age>10的数据
```php
$grid->model()
->when(!request('show_all'), function ($query) {
return $query->where('age', '>', 10);
});
```
选择后显示全部数据
```php
$grid->filter(function ($filter) {
$filter->layoutOnly()->equal('show_all', ' ')->checkbox([1 => '查看全部'])->default('');
});
```
> Layout-only filter for more custom search.

- src/Form/Field/Map.php
腾讯地图于 2018年9月30日，对JS调用必须进行key鉴权
> map组件使用腾讯地图时，增加Key鉴权

- src/Layout/Content.php
修复设置某个字段为空时失效的问题，比如
无法删除。必须中间加空格解决
->description('  ')添加了空格
> Fix an issue where some fields are invalid when they are empty

- src/helpers.php
If $path is null, "" or "/", return "/admin/" before this commit.
But Laravel default ".htaccess" setting redirects url "/admin/" to "/admin".
So I modified returning "/admin" if $path is null, "" or "/".
> modify admin_base_path if $path is null, "" or "/"

- src/Form/Field.php
- src/Form/Field/ImageField.php
使用 Filed::macro() 时候，当 Filed 类使用了 ImageField ，会先检测 ImageManagerStatic ，导致 macro 失败，改为先检测 macro 即可解决
> 修复 image 类型使用 macro 失败

- resources/assets/laravel-admin/laravel-admin.css
- resources/views/form/hasmanytable.blade.php
- src/Form/Field/HasMany.php
It is often more convenient to display some relations as a table. This commit adds support for outputting the hasMany form field as a table.
Example
$form->hasMany('keywords', 'Add more keywords', function ($nestedForm) {
$nestedForm->select('campaign_id', 'Campaign')->options(...);
$nestedForm->text('title', 'Title');
$nestedForm->checkbox('active', 'Active keyword');
...
})->useTable();
Real implementation looks like http://joxi.ru/bmovx88h3yeXZr
Css rules for correct output added to laravel-admin.css (some padding fix + validation error label)
> Table view for HasMany field

- src/Form/Field/Select.php
Using select - options function, we can get options with callback function
ex.
~~~ php
$form->select('baz')->options(function($value){
return ['1' => 'foo', '2' => 'bar'];
});
~~~
But $value property is only the value user selected.
So we cannot get other information.
(Using "$this" property in options function, we can get the model. But in "hasmany" field, "$this" is parent model, not children's model.)
So I modify.
If we want to get $field, please write as below.
ex.
~~~ php
$form->select('baz')->options(function($value, $field){
return ['1' => 'foo', '2' => 'bar'];
});
~~~ 
We can get $field instance(this example, $field is Select instance.)
If PL #2983 is OK, executing "$field->data()", We can get other's value (of course contains ID and value user edited form.)
> callback_field_in_select_options

- src/AdminServiceProvider.php
- src/Console/ExportSeedCommand.php
- src/Console/stubs/AdminTablesSeeder.stub
After the initialization of the laravel-admin, any changes to menu items, roles, permissions are saved in the local database and their transfer (from dev to prod, or to other develeper) is a problem. It is also ideologically correct to keep all the basic elements of the admin panel under the git project.
This commit adds a command
`php artisan admin:export-seed`
which generates a seed in the database/seeds in project folder.
Command has argument {classname=AdminTablesSeeder}, its allows you to set a custom name for the seed.
The --users option allows you to additionally export to seed users' tables and their relationships with roles and permissions.
Seed can be apply on another server at any time with a command
`php artisan db:seed --class=AdminTablesSeeder`
WARNING: Seed overwrites …
> Command for export current state of admin tables as a seed

- src/Form/Field/Text.php
[MDN:datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)
Implementation for Text field, datalist can be used for autocomplete function on input 
```html
<label for="ice-cream-choice">Choose a flavor:</label>
<input list="ice-cream-flavors" id="ice-cream-choice" name="ice-cream-choice" />
<datalist id="ice-cream-flavors">
<option value="Chocolate">
<option value="Coconut">
<option value="Mint">
<option value="Strawberry">
<option value="Vanilla">
</datalist>
```
Usage:
```
$form->text('flavor', 'Flavor')->datalist( Flavor::pluck('name', 'id') );
```
> datalist function for Text form field

- src/Form/Field/Currency.php
- src/Form/Field/Decimal.php
- src/Form/Field/Ip.php
- src/Form/Field/Mobile.php
- src/Form/Field/Text.php
Usage:
```
$form->text('email', 'E-mail')->inputmask([   
'mask' => '*{1,20}[.*{1,20}][.*{1,20}][.*{1,20}]@*{1,20}[.*{2,6}][.*{1,2}]',   
'greedy' => false,   
'onBeforePaste' => 'function(pastedValue, opts) { pastedValue = pastedValue.toLowerCase(); return pastedValue.replace("mailto:", ""); }',   
'definitions' => [   
'*'  => [   
'validator' => "[0-9A-Za-z!#$%&'*+/=?^_`{|}~\-]",   
'casing' => "lower"   
]   
]   
]);   
```
With some types of inputs inputmask don't work: [allowed html elements](https://github.com/RobinHerbots/Inputmask#allowed-html-elements).
So for example to make an email input with inputmask it will need to be type text.
> Add function inputmask() for Form\Field\Text::class and child classes

- src/Form.php
Hi, I found out that there are some problems with **relation update** (cannot update relations), if I have my own `Relation` class which inherits `Relations` class or using package like [chelout/laravel-relationship-events](https://github.com/chelout/laravel-relationship-events) .
Thus, I change the login of switch() in ```function updateRelation($relationsData)``` a bit, in order to accept any class which extends `Relations\BelongsToMany` class.
Please feel free to have a look on it. Thanks.
> Improve the logic of switch() closure in updateRelation function

- src/Auth/Database/Permission.php
- src/Controllers/PermissionController.php
使用Git管理代码时，Git会自动把CRLF（\r\n）转化为LF(\n)，在Linux系统下，就会出现这种情况：把permission的种子文件加入代码库->从代码库clone出permisons种子文件->把permissions种子文件导入数据库，这时在git已经把\r\n转变成了\n，所以admin_permissons表中的权限配置就只有\n分隔的路由，造成权限检查出错和下图中所示的情况。如果权限种子文件中保存了大量的权限数据，后动去更正是不在合适的。
本次提交纠正了这方面的问题。
Git will convert CRLF to LF automaticly. So on linux OS,  pull codes from repository and then run "php artisan db:seed " to initiate permissions data, because all \r have been removed, so some permission data will be wrong, and User will be denied. this commit has solved this problem.
> 优化权限检查时的兼容性

- src/Form/Field/Number.php
如果default是回调函数就会出现如下报错：
`$form->number('num', 'num')->default(function ($form) { return $form->model()->num; })->min(0);`
Object of class Closure could not be converted to int
> Number 类去掉默认值类型转换

- src/Console/MakeCommand.php
在 admin.php 文件中设置自定义目录时（将Admin的Controller文件跟项目其他Controller同级）：
```
'directory' => app_path('Http/Controllers/Admin'),
```
basename() 方法还是取到 Admin。不如获取 config('admin.route.namespace') 这个值。
> 修复当自定义Admin目录时，admin:make 命令命名空间的 bug

- src/Grid/Filter/Presenter/Select.php
grid filter select load 设置初始显示值为null。
不同于 form 的select load 要选择值，grid filter select 用于筛选，load 的下一级数据默认无需展示。
例如省市县三级过滤查询，如果查询某个省的数据，选择后，默认的市县也会出现，导致用户需要要把市县两级的select手动删除load进来的初始显示值，才能正常过滤。
> 将 grid filter select load 设置初始显示值设为 null

- src/Grid/Filter/Presenter/Text.php
Inputmask selector by is wrong after default value of filterID property updated
> Fix bug with missing input mask on filter inputs

- resources/views/partials/exception.blade.php
`env()` does not work when configuration files are cached and should only be used in config files.
`src/Form/Field/Map.php` should be updated as well, and the API keys need to moved to a config file
see [https://laravel.com/docs/5.8/configuration#configuration-caching](https://laravel.com/docs/5.8/configuration#configuration-caching)
> remove use of env() outside config files

- src/Form/Field.php
关于 issue #2807 [https://github.com/z-song/laravel-admin/issues/2807](url)
所提到的数据库字段为“ label” 会被隐藏的问题，
1. 目前的removeElementClass不能remove掉默认增加的字段名称，而且此方法目前判断是否存在class名称的方法有问题，在被array_search的数组中，如果search到第一个即key为0时，if条件将不成立，array_search在找不大目标时会返回false，所以需要判断是否返回false。
2. 新增一个resetElementClassName方法来解决默认数据库字段可能被隐藏的问题，而且不能直接unset，否则还会被追加默认字段到列的class中，所以需要将其置为需要的名称或者空。即此方法实际上是一个将class取别名的功能。
>  重设列class名称

- docs/zh/model-grid-actions.md
> 修改示例代码的语法错误

- src/Form.php
use `$form->hasMany`, IDE will report errors：function call uses more parameters than the declaration.
> fix a 'ide report errors' error

- src/Form/Field/File.php
当增加required验证字段，在编辑数据已经有原始数据的时候会提醒让重新传入文件数据
`$form->image('avatar', trans('admin.avatar'))->rules('required');`
html内容如下
`<input type="file" class="avatar" name="avatar" required="1" data-initial-preview="http://127.0.0.1:8000/vendor/laravel-admin/AdminLTE/dist/img/user2-160x160.jpg" data-initial-caption="user2-160x160.jpg" id="1556473119408_67">`
所以我在render的时候存在原始数据的情况下清除了required="1" 属性。
> Fix file field original value "required" cant submited

- src/Admin.php
当自定义 Admin Controller 目录时，会出现拼接错误
> fix router namespace

- src/Grid.php
- src/Grid/Tools/ColumnSelector.php
类似于我在控制器的Grid里
$grid->name('姓名');
$grid->age('年龄');
$grid->gender('性别');
$grid->selectColumns(['name','gender']);
然后只这么定义以后默认显示姓名和性别，年龄需要在菜单里自行勾选
> support setting ColunmSelector by default colunms

- src/Form/Field.php
When adding a class to the group, it only returned 'form-group'.
When adding an array of classes, the array_push function creates a multidimensional array and does not work correctly with the implode of the setGroupClass method.
Commented code removal.
> Fix group class in field

- src/Form/Field/UploadField.php
The file upload form had a `Cancel` button displayed to the left of the `Browse` button(bootstrap-fileinput@4.5.2).
But this `Cancel` button does not work.
In previous versions the `Cancel` button was not displayed.
So I added an option to hide the `Cancel` button by default.
[Bootstrap File Input Options - showCancel](http://plugins.krajee.com/file-input/plugin-options#showCancel)
> Add `showCancel` option to setupDefaultOption of UploadField trait

- resources/views/grid/batch-actions.blade.php
- src/Grid/Tools/BatchActions.php
批量菜单判断是否为空的逻辑，留在模板里来判断，针对想显示选中的几行，但不想有批量操作情况。目前如果$batch->disableDelete();全选那里会出现一个没有样式、非常难看的checkbox
> leave template to check batch actions empty

- src/Form.php
现在表单提交创建后的数据验证错误返回只判断了是否ajax，应该增加判断不是pjax。不然正常的表单创建只会输出一段JSON错误了
> 修复创建数据验证错误信息的返回判断

- src/Console/ExportSeedCommand.php
多人一起开发时 `admin:export-seed` 导出的seed带着id,created_at,updated_at ,不方便版本管理 不导出方便合作.
> add except-fields option to `admin:export-seed` ,增加忽略字段选项到导出命令

- src/Grid/Displayers/Modal.php
由于使用modal时，标签ID存在"."符号，无法根据ID找到元素，导致modal插件失效。
> 在使用关系列时grid modal不能正常工作

- src/Grid/Row.php
如果增加多个styles时候，会出现没有css分隔符的情况导致css失效。
> Bug fix for row style

- src/Grid/Column.php
> fixbug Parameter #1 $builder of method Encore\Admin\Grid\Column::filter() expects null, array<int, string> given.

- src/Grid/Filter.php
- src/Grid/Filter/Scope.php
**Use:**
`$filter->scopeSeparator();`
**Example:**
```
$grid->filter(function ($filter) {
$filter->scope('admins', 'Admins')->administrators();
$filter->scope('managers', 'Managers')->managers();
$filter->scope('operators', 'Operators')->operators();
$filter->scopeSeparator();
$filter->scope('actived', 'Active')->actived();
$filter->scope('deactivated', 'Not active')->deactivated();
});
```
> Scope separator

- resources/views/form/checkbox.blade.php
fix checkbox bug: when send nothing to post, the checkbox area will check the item if its value is 0
before:
after:
> bug: when send nothing to post, the checkbox area will check the item if its value is 0

- src/Form.php
- src/Form/Field/MultipleSelect.php
当关联关系的名称为多个单词时，读取关联关系的数据会失败是。
When the relation name has multi words, It does not read the relationship.
> 修正关联关系名称为多单词时无法读取关联数据的问题

- resources/views/actions/form/checkbox.blade.php
- resources/views/actions/form/date.blade.php
- resources/views/actions/form/file.blade.php
- resources/views/actions/form/help-block.blade.php
- resources/views/actions/form/multipleselect.blade.php
- resources/views/actions/form/radio.blade.php
- resources/views/actions/form/select.blade.php
- resources/views/actions/form/text.blade.php
- resources/views/actions/form/textarea.blade.php
在使用表单的时候注意到help信息不生效，检查了一下是没有引入。
至于引入应该使用@include('admin::actions.form.help-block')（新建页面）还是直接使用@include('admin::form.help-block')我很是犹豫，当前提交的版本是前者的方案。
> 修复行操作的弹出表单无法显示help信息的bug

- resources/views/content.blade.php
In some projects for segment URL not exists own page. In such cases, the breadcrumb links to the main page. Fixed.
> No URL in middle breadcrumb

- resources/views/content.blade.php
Allow the use of tags in the title and description of the content.
**Example**
```
return $content
->title("<span class='fa fa-{$report->icon}'></span> {$report->name}")
->description("for the period <b>{$report->fromdate}</b> to <b>{$report->tilldate}</b> (<span title='Report created time'>{$report->makedate}</span>)")
->breadcrumb(
['text' => 'Reports', 'icon' => 'copy'],
['text' => $report->name, 'icon' => $report->icon]
)
->body($grid);
```
> Tags in header and description content

- src/Grid/Concerns/HasActions.php
新版本全局设置为右键或者下拉操作时，无法通过文档所述为单个 grid 自定义修改为 图标模式
> 修复新版本操作列无法使用图标模式的bug

- src/Grid/Column.php
https://github.com/z-song/laravel-admin/issues/3976
使用:
```
$grid->access()
->width('200');
```
修改前:
修改后:
> fix https://github.com/z-song/laravel-admin/issues/3976

- src/Controllers/LogController.php
I finded xss from `src/Controllers/LogController.php` file. And fixed it.
Please validate it.
- STEP 1.
Access to below url.
`http://127.0.0.1:8000/admin/auth/roles?_columns_=<img src=hoge onerror=alert(document.cookie)>`
- STEP 2.
Access to below url.
`http://127.0.0.1:8000/admin/auth/logs`
> fix "/admin/auth/logs" page Authenticated Store XSS bug

- src/Grid/Filter/AbstractFilter.php
如果 $filter 多级关联的模型
$filter->like("note.profile.id");
例如，会去搜索 note 的 profile 字段
实际应该去匹配 note.profile 的 id 字段
> 解决多级关联 whereHas 的 Bug

- src/Grid/Displayers/QRCode.php
修复了二维码在带有 `overflow-x:auto`  样式的 div 内被隐藏的问题，详情： #4450
> fix: qrcode popover not visible in div with overflow hidden

- src/Grid/Exporters/AbstractExporter.php
\Encore\Admin\Grid\Exporters\AbstractExporter::getQuery() #line107
必须重新赋值：$queryBuilder = $queryBuilder->whereIn($keyName, $scope->pluck($keyName));
Because sometime $queryBuilder is a Model.
> $querybuilder reassign

- src/Grid/Actions/Delete.php
> 让删除操作保证事务一致性

- src/Console/stubs/routes.stub
bug: 加了 as 参数后，默认的 home 路由name 会变成  admin.admin.home
> fix: router name error.

- src/Form/Builder.php
判断模型`incrememting`为`true`(自增主键)时,才加入保留字段,稍后清除(removeReservedFields)
> 修正新增form表单时无法添加非自增主键的问题

- src/Form/Builder.php
这段js的开头即为小括号，倘若在这段之前的js是大括号结尾的，则这里会被解析成上个大括号结尾方法的入参，从而引发语法错误。前面添加分号可以确保与上一段代码分离。
> 修复JS隐藏语法问题

- src/Form/Field/Select.php
I'm using this template. But in editing mode, city field not selected by the "selected" value. Only selects first value.
```
$form->select('province')->options(...)->load('city', '/api/city');
$form->select('city');
```
Example usage
```
if ($form->isCreating()) {
$form->select('city');
} else {
$form->select('city')->default($form->model()->city);
}
```
Now, looking for value from data-value attribute. If exists, set the value than trigger change.
> Set value for select in editing mode

- src/Grid/Exporters/CsvExporter.php
refer issues #4733 
搭配 export->column，用户现在有足够工具自行转码了。
> 数据导出添加 export->title 方法，允许定制修改 CSV 表头

- src/Form/Field/MultipleFile.php
多图上传如果加上sortable() 时就会在页面增加 _file_sort_字段，此处的判断正好阻止了获取图片的验证规则，导致多图上传时验证规则失效，直接删除该代码即可，我看到之前有人已经提了这个问题的PR ，但是修改方法不是太好，该判断没有任何意义，因为这里不像删除图片是异步。排序是和修改一块提交的，所以删除代码即可
> 多图上传使用排序功能时会导致获取不到图片验证规则

- src/Form/Field.php
当 hasMany使用 table 时，表格内的 label 被添加了hidden类以隐藏，但如果此时设置了required属性，则会添加了asterisk类覆盖掉了hidden类，以致显示错误。
本来计划改为 array_merge的，但又考虑到有需要覆盖的可能，故加了一个参数以确定是覆盖还是合并
> 修复标签样式类被覆盖问题

- src/Form/Field/Checkbox.php
在最新的v1.8.2中，不同的JS代码合并到一行，导致没有加“ ; ”的JS语句出错
> v1.8.2JS问题修复

- src/Form/Field/Image.php
修复无后缀网络图片无法正常显示问题 例如微信头像: https://thirdwx.qlogo.cn/mmopen/vi_32/xxxx/132
> force file type to image with Image field

- src/Grid/Model.php
$this->relation 本身已经有__call方法直接调用query的方法了，不必再getQuery()，而且使用了getQuery()得到的builder，不会去获取pivot关系表内容，需要relation模型才可获取
> 修改模型relation的get方法

- resources/views/components/column-modal.blade.php
原来的modal节点获取方式是通过.grid-madal，同时监听了不同的modal，导致都触发了事件，应当用ID形式获取每个独立的modal，分别监听各自事件
> 解决多个async modal同时出现时冲突问题

- src/Grid/Column/RangeFilter.php
reproduce: apply a range filter with 'start' field blank, then apply other filters
> Fixed "Undefined index start/end" in range filter

- resources/views/filter/multipleselect.blade.php
After using `multipleSelect` filter with dot-notation (e.g. `categories.id`), `option` elements don't have `selected` prop.
In the template `views/filter/multipleselect.blade.php`, `request($name, [])` is used to get current value, but it will always be `[]` when dot-notation is used. I fixed that with the use of `$value` passed from controller instead of `request($name)`. I would appreciate it if you could confirm this.
> Fix multiple select filter

- src/Form/Field/ImageField.php
- src/Form/Field/MultipleFile.php
- src/Form/Field/MultipleImage.php
== FIXES ==
Refactored thumbnail delete logic into separate method in  src/Form/Field/ImageField.php
Added thumbnails  loop  when deleting the image field file in   src/Form/Field/MultipleFile.php
Implemented same logic as single Image field prepare without changing return value in  src/Form/Field/MultipleImage.php
> Multiple Image Upload thumbnail creation and deletion fix.

- src/Grid/Tools/QuickCreate.php
解决：https://github.com/z-song/laravel-admin/issues/5018
> 解决当详情页使用grid时快速创建请求地址为当前网址的问题

- src/Form/Field/CanCascadeFields.php
```php
$form->radio('nationality', '国籍')
->options([
1 => '本国',
2 => '外国',
])->when(1, function (Form $form) { 
$form->text('name', '姓名');
$form->text('idcard', '身份证');
})->when(2, function (Form $form) { 
$form->text('name', '姓名');
$form->text('passport', '护照');
})->default(2);
```
在点击新增按钮创建表单时，并没有出现默认设置的姓名和护照这个两个联动项
> 修复 模型表单/表单联动 创建新表单 设置默认表单项，没有联动显示默认设置的其他表单项bug。

- resources/views/table/quick-create/form.blade.php
直接用serialize提交post会没有数据，但是serializeArray就不会，具体原因不明。
>  在 quick create 中使用 serializeArray

- src/Grid/Displayers/RowSelector.php
修复列表checkbox选择后刷新继续保存checked状态，导致刷新后点击下载选择行无效
> 修复列表checkbox选择后刷新继续保存checked状态，导致刷新后点击下载选择行无效

- src/Grid/Column/CheckFilter.php
- src/Grid/Column/InputFilter.php
- src/Grid/Column/RangeFilter.php
如：$grid->column('name','赠品名称')->filter('like'); 点击列过滤弹出的重置按钮点击达不到预期效果， 其效果等同于submit， 而不是reset。
源码：` <button class="btn btn-sm btn-flat btn-default column-filter-all" data-loading-text="..."><i class="fa fa-undo"></i></button>`
优化方法1：button标签添加 type='reset' (CheckFilter中有type设置， 其它两个类没有 )。 但是该方式依旧不能很好清除用户输入。
优化方法2：使用a标签代替。
`<a href="{$this->getFormAction()}" class="btn btn-sm btn-flat btn-default"><i class="fa fa-undo"></i></a>`。 
其做法参考于“重置”按钮
之所以在a标签外再套一个span， 是因为css作用冲突偏移（.dropdown-menu>li>a{ }  改样式作用级别比a标签的class高）
> Grid filter 列过滤的reset按钮功能无效

- src/Grid/Exporters/CsvExporter.php
导出的CSV文件是无BOM编码UTF-8，在Windows的Excel打开时会乱码。所以添加BOM于CSV中
> add utf-8 bom to csv exporter

- resources/views/grid/inline-edit/switch.blade.php
``` php
$states = [
'on'  => ['value' => 0, 'text' => '正常', 'color' => 'primary'],
'off' => ['value' => 1, 'text' => '停用', 'color' => 'danger'],
];
```
Field for this value accept 'Integer' only, model()->save() did nothing for value 'on' and 'off'.
> fix: inline-edit passes error value to model

- resources/views/grid/inline-edit/switch-group.blade.php
The SwitchGroup component has the same problem with PR #5304 as switch.
> fix: inline-edit passes wrong value to model

- resources/views/form/checkbox.blade.php
- src/Form/Field/Checkbox.php
Groupping feature like select optgroup.
Example:
```
$form->checkbox('group1', __('Groupped Checkbox 1'))
->groups(
[
'Group 1' => [
'key1' => 'Value 1',
'key2' => 'Value 2',
],
'Group 2' => [
'key3' => 'Value 3',
'key4' => 'Value 4',
'key5' => 'Value 5',
],
]
);
$form->checkbox('group2', __('Groupped Checkbox 2'))
->groups(
[
'Group 1' => [
'key1' => 'Value 1',
'key2' => 'Value 2',
],
'Group 2' => [
'key3' => 'Value 3',
'key4' => 'Value 4',
'key5' => 'Value 5',
],
]
)
->canCheckAll();
```
Form output:
> Groupping support for checkbox options

- src/Form.php
- src/Form/Field.php
主要是修复了如下代码在 `edit` 页面的时候获取不到值：
```
$form->xxx('fooBar.field', __('字段')) // xxx 代表 form 的函数
$form->range('fooBar.field1',  'fooBar.field2', __('字段')) 
```
> 当 form 参数形式为'驼峰.字段名'时，获取不到字段的值

- resources/views/filter/between.blade.php
- src/Grid/Filter/Presenter/Text.php
Hello there,
I modified the biteween filter to allow integer(), decimal(), currency(), etc.
`$filter->between('amount',__('数量'))->integer();`
`$filter->between('distance',__('距離'))->decimal();`
`$filter->between('price',__('価格'))->currency();`
Regards, Takkkken
> Fixed to allow many inputmask type in between filter.

- src/Actions/Interactor/Form.php
```
public function form()
{
....
$this->radio('status', __('admin.status'))->options($status)->rules('required');
$this->textarea('login_remark', __('admin.Login remark'))->rules('required');
}
```
设置验证规则后，错误的数据，按钮一直显示loading，且无法继续第二次提交; 
ajax 验证错误后没有重置button;
```
// Encore\Admin\Actions\Interactor\Form.php
protected function buildGeneralActionPromise()
{
....
$.ajax({
method: '{$this->action->getMethod()}',
url: '{$this->action->getHandleRoute()}',
data: formData,
cache: false,
contentType: false,
processData: false,
success: function (data) {
resolve([data, target]);
if (data.status === true) {
$('#'+modalId).modal('hide');
}
// 还原按钮
$(':submit', '#'+modalId).button('reset');
},
error:function(request){
reject(request);
}
});
....
}
```
> Fix validation error, unable to submit repeatedly

- src/Form/EmbeddedForm.php
当同时使用 `$form->when()` 和 `$form->embeds()` 的时候有可能会出现此处 `$field` 为 null 的情况, 兼容一下.
> Make sure `$field` is valid

- src/Console/GenerateMenuCommand.php
This PR solves hard-coded route-prefix(admin) issue when execute `php artisan admin:generate-menu` command.Because this prefix value can be changed dynamically at `admin.route.prefix` value in config.
```
'route' => [
'prefix' => env('ADMIN_ROUTE_PREFIX', 'zero'),
'namespace' => 'App\\Admin\\Controllers',
'middleware' => ['web', 'admin'],
],
```
> Adds config-based route prefix to GenerateMenuCommand.php

- src/Grid/Model.php
如果grid的某一列为json，排序时会导致sql报错：
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'prefix_JSON_EXTRACT(json, '$.json_column')' in 'order clause' 
原因是json处理后的排序字段：
会在执行时被laravelORM的Gammer转译（增加前缀和``）
所以在增加针对json字段特殊处理：
> fix grid json column sortable error

- src/Form/Field/Checkbox.php
PHP 7.0.33
Laravel 5.5
我用php7.0.33装1.8.16，刚开始我以为是版本的问题，就降了一个版本，装了1.8.15,也有这个问题。再看Requirements,是支持7.0版本的。
```txt
"Declaration of Encore\Admin\Form\Field\Checkbox::groups($groups = Array) should be compatible with Encore\Admin\Form\Field\Select::groups(array $groups)"
```
> fix declaration of Encore\Admin\Form\Field\Checkbox::groups

- src/AdminServiceProvider.php
配置项的名称是 admin_https，那么该配置的作用域不应该超出 /admin* 的范围，即不应该去影响非后台路由，一旦这里影响了，后续想要在其他页面做 http 和 https 的兼容会很麻烦
> 将配置项 admin_https 的作用域限制到 /admin*

- resources/views/grid/inline-edit/switch.blade.php
When switch change has validation errors, When the state of the switch changes and there is a validation error, an empty warning appears and a JS error occurs in the console.
At the same time the visual state of the switch changes.
This commit displays an error message and does not change the visual state if an error occurs.
> Show validation errors when switch changed

- src/Admin.php
- src/Widgets/Box.php
In documents and views, `favicon()` was used like:
```php
Admin::favicon('favicon.png');
```
```php
@if(!is_null($favicon = Admin::favicon()))
<link rel="shortcut icon" href="{{$favicon}}">
@endif
```
However, in **Encore\Admin\Admin**, it is inconsistently designated as `public function` rather than `public static function`. It doesn't affect actual usage right now but it is an inconsistency that should be fixed.
```php
/**
* @param null|string $favicon
*
* @return string|void
*/
public function favicon($favicon = null)
{
if (is_null($favicon)) {
return static::$favicon;
}
static::$favicon = $favicon;
}
```
> fixed favicon method inconsistency with document and usages

- src/Show/Field.php
add JSON_UNESCAPED_UNICODE bitmask to json_encode() method to encode multibyte Unicode characters (for example, Chinese characters) literally (default is to escape as \uXXXX).
> encode multibyte Unicode characters literally

- src/Auth/Database/Administrator.php
高版本的php中对preg_match()的严谨入参，如果第二个参数传`null`，则会发生以下错误。
```
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 625
```
> 修正preg_match()函数第二个参数需要为字符串
