z-song/laravel-admin

- src/Form.php
```php
public function form()
{
return Admin::form(File::class, function(Form $form)
{
$form->saved(function(Form $form) {
// do something after saving
});
});
}
```
> Hook into the Form after saving

- src/Form.php
- src/Form/Field.php
And gives the Fields access to the managed model object of the form.
see #5 and #10
> This allows adding custom Form Fields.

- src/Auth/Permission.php
- src/Form/Field.php
- src/Widgets/Box.php
- src/Widgets/Callout.php
@z-song requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/z-song/laravel-admin/
> Scrutinizer Auto-Fixes

- views/login.blade.php
感觉会有好多地方要放，config('admin.name')这种的感觉也要改下好，我这块目前还在弄，最好views里机的关于config都从Admin里输出好点
> unify url output

- src/Grid/Filter/AbstractFilter.php
- src/Grid/Filter/Field/Text.php
- views/filter/text.blade.php
在AbstractFilter类增加了一个魔术方法，Text类增加了placeholder属性及set方法。
> make input placeholder customizable

- src/Form/Field/HasMany.php
- src/Form/NestedForm.php
1. 解决NestedForm 内 setElementName, setElementClass 和 setErrorKey 的顺序问题
2. 解决NestedForm 内的 $field->form 为 null 的 BUG
> format $field when it __call

- src/Admin.php
- src/Grid/Model.php
It should return the full config('admin.directory') path relative
to the app()->basePath()
> Admin->controllerNamespace() function only handles one level of directory

- src/Form/Field/MultipleSelect.php
change `getOtherKey` to `getQualifiedRelatedKeyName`
> Fix MultipleSelect for Laravel 5.4

- views/grid/filter.blade.php
- views/grid/table.blade.php
> fix grid filter layout on smaller devices

- views/form/multipleselect.blade.php
解决multipleselect.blade.php 的宽度问题。
> fix multipleselect width

- src/Grid/Displayers/Editable.php
editable 的 select 控件显示值不应该跟value一样。
> fix select html display value

- lang/ru/lang.php
ps: admit the possibility that there is a specific error
> [TR] Add Russian translations

- views/form/tags.blade.php
Same as in other views with a select
Tags component didn't show up in full width when use in a tab
> fix Tags field width issue

- src/Grid/Filter.php
- src/Grid/Filter/AbstractFilter.php
同 [#633](https://github.com/z-song/laravel-admin/issues/633)
> 修改Encore\Admin\Grid\Filter::addFilter为public以自定义过滤器

- views/index.blade.php
Hey, 
I just add charset utf-8 to fix broken characters in js AlertBox.
I have override the template in my project but I made this PR because I think it can be usefull for everyone !
Thank for your work!
> Add charset utf-8

- src/Form/Field/File.php
文件字段是关联表里面是$input[$this->column]出错。
> 关联字段$this->column 读取name.name的属性出错

- src/Form/Field/SwitchField.php
This way you can detect changes on the switch using external JS
```JS
$('.selector').bind('change', function(){
console.log('it changed!', $(this));
});
```
> Trigger change event on switch field when changed

- src/Form.php
Add support for MorphOne relation next to HasOne relations
fixes #902
> Add support for MorphOne relation

- resources/views/form/select.blade.php
Select2 need to have empty option so it select empty option as default value...
Select2需要有空选项，因此选择空选项为默认值… ^^
> Select2 need to have empty option (Select2需要有空选项)

- src/Grid/Exporters/CsvExporter.php
Recent changes in fix for #1257 break all my custom exporters. 
My custom exporters overwrote the 'getData' function to transform the csv in the data I wanted.
These recent changes now skip the getData() function completely :(
My PR adds extra methods uses by the export function so classes that extend CsvExporter can overwrite data more easily. Otherwise we have to overwrite the whole export() function
> Make CsvExporter extendable

- src/Grid/Filter/Presenter/DateTime.php
: void return type is php 7.1
please remove others as well globaly (all in the presenter classes)
> remove php 7.1 dependency

- src/Grid/Filter.php
extra fix for disappearing first filter (#1356)
> extra fix for disappearing first filter (#1356)

- src/Form/Builder.php
"save" button text for "MODE_EDIT" and "submit" for others (just for "MODE_CREATE")
> fix submitButton() text @ Builder.php

- resources/views/widgets/form.blade.php
- src/Widgets/Form.php
https://github.com/z-song/laravel-admin/issues/1599
> Widgets\Form - delete csrf_token from GET request

- resources/lang/pt/admin.php
Simply added a PT_PT Language Translation, it can also be easily understood by PT_BR speakers but in the future it would be good to have a PT_BR version as well.
> Added PT-PT translations file

- src/Grid/Filter.php
增加设置grid  filter  modal的id，实现同一个页面多个表格筛选功能
> 增加设置grid  filter  modal的id，实现同一个页面多个表格筛选功能

- resources/lang/es/admin.php
Hello, I am improving the spanish translations
> Fix spanish translate

- resources/lang/ja/admin.php
I have created it because there was no translation for Japanese speakers.
> Added Japanese translation

- src/Form/Field/Mobile.php
Way to send javascript functions over JSON like JS object, not a string.
String with JS function MUST start with `function(`
> Update Form->Mobile.php: JS function as option value

- resources/lang/ar/admin.php
> Added Arabic translations

- src/Form.php
I'm using Laravel Admin because many features but my application is Single Page Application. So, i'm using Form features to validate and save data. But if i could to have a $data parameter to update method ll be very usefull to me.
> Add $data parameter to update form function

- docs/en/extension-media-manager.md
- docs/zh/extension-media-manager.md
> docs(extension): update media-manager access url

- config/admin.php
- resources/views/login.blade.php
> 添加登陆页背景图片配置

- resources/lang/pt-BR/admin.php
Add language brazillian portuguese.
> Add language PT-BR

- src/Grid/Displayers/Checkbox.php
> Grid-CheckBox can't submit empty array

- composer.json
- resources/lang/fa/admin.php
Make localization file for Persian language
> V1.5.14 fa

- src/Auth/Database/Menu.php
> fix bug for issue #2121

- docs/en/model-grid-filters.md
Because laravel-admin is very powerful!
> Document a way to make complex filters

- src/Form/Field.php
Please let us make use to it 🙏
> Make Form\Field::variables() public

- composer.json
- src/AdminServiceProvider.php
- src/Console/FormCommand.php
for example:
```bash
php artisan admin:form --model=App\\User
```
this command is very useful.
> add a command:form filed generator

- resources/views/grid/table.blade.php
- src/Form/Tools.php
ver1.5.18, in Form/Tools.php, add initialization $appends and $prepends.
> bug fix for Form/Tools.php, and ad thead and tbody in views/grid/table.blade.php

- docs/en/model-form-fields.md
- docs/zh/model-form-fields.md
增加接口路由的提示，当 route.prefix 配置被修改时。
> Add notice in the docs

- src/Grid/Exporters/AbstractExporter.php
- src/Grid/Filter.php
sometimes we need eloquent model object to do something others.
> allow AbstractExporter getData() return collection

- src/Console/stubs/controller.stub
> Remove extra spaces

- resources/views/form/footer.blade.php
- resources/views/widgets/form.blade.php
- src/Form.php
- src/Form/Field/Email.php
- src/Form/Field/Ip.php
- src/Form/Field/Url.php
- src/Form/Footer.php
- src/Widgets/Form.php
- Appended disableViewCheck and disableEditingCheck in Form. If add on form function, disable view, editing checkbox on footer.
- Appended disableReset and disableSubmit in Widgets\Form. If add on form function, disable Reset, Submit Button on footer.
- Email, Url, Ip field has rules default. But if user wants to save as empty, but has errors because empty is not match rules (ex. empty is not email.)
So I added "nullable" rules as default. If developer wants to add require rules, write "rules('required')" in Controller form field.
> Add disableViewCheck and disableEditingCheck, etc. And bug fix IP, Email, Url field.

- src/Admin.php
在Admin里面增加一个noPjax的函数
在Controller里面，可以直接使用Admin::noPjax(); 来控制当前页面是否使用Pjax
这样可以增加使用Pjax的灵活性
> 增加控制函数，让控制器可以自行定义当前页面是否使用pjax

- resources/views/form/checkbox.blade.php
- resources/views/form/radio.blade.php
- src/Form/Field.php
- src/Form/Field/Checkbox.php
- src/Form/Field/Radio.php
for example:
```
$form->radio('columnName')->options([0,1,2,3,4])->checked(1);
$form->checkbox('columnName')->options([0,1,2,3,4])->checked([1,2]);
```
> Add checked method for input radio and checkbox

- src/Form/Field.php
Specifies a regular expression against which to validate the value of the input.
> Add pattern method

- src/AdminServiceProvider.php
- src/Console/PublishCommand.php
参考自：https://nova.laravel.com/docs/1.0/installation.html#updating-nova
> Add admin:publish command

- config/admin.php
function admin_path() call config()，it will return null when called in config file.
> change config item: extension_dir default value

- resources/views/index.blade.php
> 修复无法复写样式的 bug

- src/Form/Field/Html.php
- views/form.blade.php
- views/form/button.blade.php
- views/form/captcha.blade.php
- views/form/checkbox.blade.php
- views/form/daterange.blade.php
- views/form/datetimerange.blade.php
- views/form/display.blade.php
- views/form/editor.blade.php
- views/form/file.blade.php
- views/form/hasmany.blade.php
- views/form/id.blade.php
- views/form/input.blade.php
- views/form/map.blade.php
- views/form/multiplefile.blade.php
- views/form/multipleselect.blade.php
- views/form/radio.blade.php
- views/form/rate.blade.php
- views/form/select.blade.php
- views/form/slider.blade.php
- views/form/switchfield.blade.php
- views/form/tags.blade.php
- views/form/textarea.blade.php
- views/form/timerange.blade.php
- views/helpers/scaffold.blade.php
- views/widgets/form.blade.php
Added "row" class to parent div that contains children with "col-sm-*" class. This is necessary(!) for bootstrap layout because it adds clear style to prevent layout breaking.
> Added "row" class name

- src/Form/Field/Select.php
- src/Grid/Filter/Presenter/Select.php
Enable select2 support config method for remote data source
> optimize select2 config method

- src/Form/Field/HasMany.php
- src/Form/NestedForm.php
Fix the issue that multipleImage cannot be displayed correctly and cannot pass the form validation in NestedForm.
> improve: support multipleImage  in NestedForm

- src/Console/InstallCommand.php
- src/Console/MenuCommand.php
- src/Console/PublishCommand.php
- src/Console/UninstallCommand.php
主要是修复`PublishCommand`问题，使用`$name`无法支持 `--force` 参数
> change command parametes $name to $signature

- resources/views/tree.blade.php
https://github.com/z-song/laravel-admin/issues/2547
> Fix Collapse in the model-tree

- src/AdminServiceProvider.php
- src/Form.php
Hello, for test, after merge clean project cache
> Better SSL support, removed # fix #1768

- resources/views/content.blade.php
Show default breadcrumb if breadcumb not defined in controller
> Add default breadcrumb

- src/Grid/Model.php
fix for issue #2283 - after relation sort column with eq. name in main \ relation table set eq. values
> Fix relation sort (issue #2283)

- config/admin.php
A skin url is not found.
https://adminlte.io/docs/2.4/skin => https://adminlte.io/docs/2.4/layout
> Change Skin url

- src/Admin.php
- src/Console/InstallCommand.php
- src/Console/stubs/AuthController.stub
- tests/InstallTest.php
hi，`laravel-admin` login built-in validation has done good enough, but I hope to be able to put `AuthController`user directory, as well as` laravel`.So that users can override some of the parent method to get the results they want.
> The login authentication let users can easily handle in the source code

- resources/views/grid/batch-actions.blade.php
- src/Grid/Tools/BatchActions.php
目前disableDelete方法可以去除删除按钮但是会把全选按钮一起去掉,实现了一个方法来保留全选按钮然后通过自定义工具实现想要的全选样式以及全选功能
> 增加关闭批量删除但是保留左侧多选框的方法

- src/Grid/Displayers/Image.php
> Fix base64 image can not display

- docs/en/model-grid.md
- resources/views/grid/table.blade.php
- src/Grid.php
> disableTools method for grid

- resources/assets/laravel-admin/laravel-admin.css
> Unique file name doesn't fit the box

- resources/assets/jquery-pjax/jquery.pjax.js
- src/Tree.php
- fix: loading of scripts in pjax containers
- fix: expand and collapse button invalid when clicking on the child elements under <a> tags
> Fixed loading of scripts in pjax containers and button clicks invalid

- src/Form.php
> [fix]#1235 hasOne relation should use localKey

- src/Grid/Tools/CreateButton.php
Use "fa-plus" icon instead of "fa-save" for create button
> Use better icon for create-button of Grid

- src/Widgets/Table.php
Add ability to set style for table widgets.
> Styleable tables

- docs/en/model-form-callback.md
The submitted form callback function is not in the documentation, but can be useful to change the behaviour once the form has been submitted
> Add details of submitted form callback function

- src/Grid.php
add check on Relations\MorphToMany instance in handleRelationColumn method of Grid class.
> added morpgOne relation to Grid

- src/Grid/Column.php
Add "sort" function. this function sets $sortable value true/false.
Set value from controller whether sort enable/disable
> add sort function in Grid/Column

- src/Form.php
Form类添加一个禁止显示表单底部"继续创建"的方法 , 这样表单的底部可以自由定义是否显示这个checkbox
> Form类添加一个禁止显示表单底部"继续创建"的方法

- resources/views/form/hasmany.blade.php
- src/Form/Field/HasMany.php
How to use
```
$form->hasMany('orders', function (Form\NestedForm $form) {
$form->text('id');
$form->text('description');
})
->disableCreate()
->disableDelete();
```
Issue #1027
> Disable "New" or "Remove" with NestedForm #1027

- resources/views/form/hasmany.blade.php
- src/Form/Field/HasMany.php
> Disable "New" or "Remove" with NestedForm #1027 #2836

- resources/views/filter/select.blade.php
> fixed: [filter]设置默认值为整型时select无法选中的问题

- src/Admin.php
Set custom admin title, for dev version
`Admin::setTitle('Hello');`
> Set custom title on admin page #2878

- src/Middleware/OperationLog.php
Should fix #625 
Hides passwords and tokens from operations log
> Password hide from operations log

- tests/FileUploadTest.php
> extension bug

- src/Grid/Filter/Presenter/MultipleSelect.php
当前select 只有load方法来实现二级联动，但是上级不支持多选，
所以添加了loadMore这个方法
> 多级联动，上级支持多选

- config/admin.php
- resources/views/login.blade.php
- src/Controllers/AuthController.php
Add checkbox "Remember" in login form, can turn off in admin config
> "Remember me" in login form

- resources/views/partials/exception.blade.php
exception errors should not show in production and debug disabled mode!
> exception errors should not show in production!

- config/admin.php
If you want to change admin route prefix, set parameter "ADMIN_ROUTE_PREFIX" in .env.
> add config 'ADMIN_ROUTE_PREFIX'

- src/Form/Field.php
有时需要在 Field::macro() 时决定是否显示，在 Filed 上增加此方法可以解决
> Add setDispaly function

- src/Form/Field.php
Fix function setElementClass() from Form\Field.php overwriting element classes.
> Fix function setElementClass()

- src/Form/Field.php
> Fix function setScript() in Form\Field

- src/Form/Field.php
add setView function to Field Class
> add setView function to Field Class

- src/Form.php
The builder was not created with trashed models
> Fix softdelete edit

- src/Form.php
- src/Form/Footer.php
- src/Form/Tools.php
- src/Grid.php
- src/Grid/Displayers/Actions.php
- src/Grid/Filter.php
- src/Grid/Tools.php
- src/Grid/Tools/AbstractTool.php
- src/Grid/Tools/BatchActions.php
- src/Show.php
- src/Show/Tools.php
本次合并对Grid, Form以及Show提供给用户在全局无痛设置buttons和checkboxs的默认行为的方法。
> Grid form init

- src/Form.php
Fixes z-song#1568 Polymorphic Relations
> Fixes MorphTo Relationship Fields in Forms

- src/Form/Field/Select.php
Select2 ReadOnly的PR 
1.移除特定字段名称,增加MultipleSelect的修订
> 单独的Select2 ReadOnly

- src/Grid/Displayers/Actions.php
BugFix for https://github.com/z-song/laravel-admin/issues/3078
> 模型设置了getRouteKeyName但是编辑链接不起作用

- src/Grid/Displayers/Editable.php
理论上应该对用户的任何输入都要进行过滤，所以开始是想在column类层面直接对获取到的所有用户输入数据进行过滤，但怕如此操作会影响到一些未知的组件正常运作，因此退而仅对editable产生的xss问题做修改。
> fix editable component xss bug

- src/Form/Field.php
解决方法：给每个$form->image的 添加一个唯一class
> 修复内容 ：form组件 一对多下 $form->image 组件无法正常使用

- src/Grid/Tools/ColumnSelector.php
> Column selector buttons translation

- src/Form/Field/Text.php
> Embeds和HasMany字段名与外面主Form字段名重复时,显示主Form字段值的问题

- src/Form/Tab.php
详见https://github.com/z-song/laravel-admin/issues/3149
> [BUG-FIX]同一页面无法有多个带TAB的表单

- src/Form.php
- src/Grid/Model.php
BelongsTo::getForeignKey()->BelongsTo::getForeignKeyName()
> 兼容laravel 5.8 BelongsTo::getForeignKey()->BelongsTo::getForeignKeyName()

- src/Grid/Filter.php
- src/Grid/Filter/LeftLike.php
add grid filter left support
example code:
```php
$grid->filter(function ($filter) {
$userModel = config('admin.database.users_model');
$filter->equal('user_id', '用户名')->select($userModel::all()->pluck('name', 'id'));
$filter->leftLike('name', '昵称');
// $filter->like('name', '昵称');
});
```
> Add filter left like

- docs/en/content-layout.md
Document for create custom view file.
> Create custom page

- docs/en/model-form-fields.md
- src/Form/Field/Text.php
Example
$form->text('name', 'Slug')->addIcon('fa-copy');
> Add icon to text input on Form

- docs/en/content-layout.md
Showing where to add blade file location.
> Update Blade view file location

- src/Form/Field/Select.php
Remove unnecessary console.log() from select change event.
> Remove unnecessary script code

- src/Form/Field/Table.php
$form->table 对于多对多的数据再修改的时候不能显示出默认数据，这个改动能让 table 处理多对多的显示出默认数据。
> 增加 $form->table 对多对多情况的数据显示 

- resources/views/grid/table.blade.php
- src/Grid/Displayers/Actions.php
> 给grid的列加上class以方便控制

- src/Grid/Tools/ColumnSelector.php
Fix column-select-all button class name error
> [fix] column-selector column-select-all button class name error

- src/Form/Field/Select.php
- src/Form/Field/SwitchField.php
- src/Grid/Filter/Presenter/Select.php
1. 修正 jQuery ajax因传入url带默认参数导致请求错误bug
2. 前端Switch组件支持设置按钮Size
> 修正一处Ajax请求错误和前端switch组件改进

- src/Form/Field/HasMany.php
> 修正hasMany内->table新增事件污染到hasMany新增

- src/Console/MakeCommand.php
Model: `OrderItem`
Bad: `orderitems`
Better: `order-items`
> convert the route to kebab-case

- src/AdminServiceProvider.php
- src/Console/PermissionCommand.php
> add admin:permissions command

- src/Controllers/UserController.php
If has multiple connections the validation needs the connection.
Only get the connection from config and apply this in UserContoller
> change for manage multiple connection in validation form user

- src/Grid/Displayers/Link.php
> Grid的link方法支持自定义回调函数赋值

- resources/views/grid/table.blade.php
> add table-responsive

- src/Form/Field/UploadField.php
> remove possible parameters from string. close #3598

- src/Form/Field/ImageField.php
> 增加自定义缩略图裁剪方式的参数

- resources/assets/laravel-admin/laravel-admin.js
Clear selects after grid was reloaded
> 页面刷新后清空Grid已选

- resources/views/partials/sidebar.blade.php
> 菜单搜索增加语言本地化支持

- resources/lang/tr/admin.php
Missing translation is completed for Turkish
Thanks
> Turkish translation

- resources/views/login.blade.php
- resources/views/partials/header.blade.php
- resources/views/partials/menu.blade.php
- resources/views/partials/sidebar.blade.php
- src/Grid.php
- tests/UserGridTest.php
原本的admin_base_path会导致项目部署在二级目录出现问题
> 修复视图中的路径问题

- src/Form.php
- src/Grid/Model.php
Compares two "PHP-standardized" version number strings
https://www.php.net/manual/en/function.version-compare.php
> use version_compare

- src/Form/Field/UploadField.php
> fix preview  play of mp3 file

- resources/views/partials/header.blade.php
> '小屏幕时header显示不正常修复'

- src/Auth/Database/Menu.php
> fix Menu generation fails with MSSQL Server #1918

- resources/views/grid/batch-actions.blade.php
> grid batch action when in xs screen should hide a btn

- src/Extension.php
- src/Form/Field/HasMany.php
- 修改 Encore\Admin\Extension 
在导入扩展的时候, 支持 子菜单导入 以及 多权限 导入
- Encore\Admin\Form\Field\HasMany 添加 distinctFields 方法, 可将相关字段添加 'distinct' 验证
> Submenu feature when import extension

- src/Form/Field/ImageField.php
- src/Traits/Resizable.php
str_replace_last  ->  Str::replaceLast
> Replace old "str_replace_last" function.

- src/Form/Field.php
fix https://github.com/z-song/laravel-admin/issues/4034
> fix return type declarations

- src/Grid/Column/CheckFilter.php
- src/Grid/Column/InputFilter.php
- src/Grid/Column/RangeFilter.php
The column filter form does not look very nice in russian language. The buttons title is too long. I suggest replacing with icons. Also changed the text in "data-loading-text".
> Column filter buttons

- src/Auth/Database/HasPermissions.php
> boot to bootHasPermissions

- src/Form/Field/Select.php
> fixed the problem that (bool) false is interpreted to ' ' in text

- src/Grid/Displayers/DropdownActions.php
> fix 行操作BUG #3924

- src/Form/Builder.php
禁用 pjax 后，hasFile 判断有问题，需要增加 MultipleFile 的判断
> fix hasFile

- src/Grid/Model.php
- tests/MenuTest.php
- tests/TestCase.php
- tests/UserGridTest.php
- tests/controllers/UserController.php
- tests/migrations/2016_11_22_093148_create_test_tables.php
- tests/models/User.php
- tests/seeds/UserTableSeeder.php
Now we can't sort by JSON field, but i need that feature on my project. Can you merge my fix? Or tell me what i need to change in PR for it.
Thanks
> Sort by JSON field in grid

- src/Form/Field/Table.php
创建页面无法打开抛出异常
```php
Invalid argument supplied for foreach() (View: /home/vagrant/code/order-system/vendor/encore/laravel-admin/resources/views/widgets/form.blade.php)
vendor/encore/laravel-admin/src/Form/Field/Table.php:54
...
//调试发现$this->value为null
foreach ($this->value as $key => $data) {
if (isset($data['pivot'])) {
$data = array_merge($data, $data['pivot']);
}
$forms[$key] = $this->buildNestedForm($this->column, $this->builder, $key)->fill($data);
}
...
```
> Form table字段新建数据时报错

- src/Form/Field/MultipleFile.php
> @return array.

- src/Grid/Filter/Scope.php
使用范例
```php
$grid = new Grid(new Order);
$grid->filter(function (Filter $filter) {
$filter->scope('unpaid', '未支付')->where('status', Order::STATUS_UNPAID);
$filter->scope('paid', '已支付')->where('status', Order::STATUS_PAID)->asDefault();
});
```
> 给 scope 加上 asDefault() 方法

- src/Grid/Column.php
> Fixed dot in grid 

- src/Actions/Interactor/Form.php
- src/Form/Field/Text.php
> Interactor\Form 支持 table && Text 增加方法决定是否显示 icon

- src/Form.php
> 修正isEditing判断

- src/Grid/Column/Help.php
make grid column help message can contian html code
> grid column help optimization

- resources/views/actions/form/multipleselect.blade.php
$select变量指每一个选项的key，无法和$value做比较
> action内的multiselect无法设置默认值Bug

- src/Grid/Concerns/HasHotKeys.php
- src/Grid/Filter/AbstractFilter.php
- src/Grid/Filter/Presenter/Text.php
See issues: https://github.com/z-song/laravel-admin/issues/4653
> Optimize grid hotkey and fix a js bug in Encore\Admin\Grid\Filter\Presenter\Text::inputmask()

- src/Form/Field/CanCascadeFields.php
- src/Form/Field/Select.php
Signed-off-by: kaodou <83516047@qq.com>
1.多选框表单联动增加两个case
2.select多选框只读是后面的选项还是可以删除操作
> https://github.com/z-song/laravel-admin/issues/4784

- resources/views/filter/betweenDatetime.blade.php
> bugfix: set autocomplete=off for "between date" filter

- resources/views/form/keyvalue.blade.php
- resources/views/form/listfield.blade.php
> 修复keyValue,list编辑时页面底部出现异常

- src/Grid/Displayers/Expand.php
> 关联字段列展开expand错误

- src/Assets.php
> 修复fileinput控件图标不显示问题

- src/Actions/Action.php
fix conflict with multiple same action at same page
> fix conflict with multiple same action at same page

- resources/views/table/display/modal.blade.php
- src/Table/Displayers/Modal.php
> 修复多次触发 modal

- src/Form/Field/Embeds.php
Implemented the workaround from the ticket #899 to the embeds field.
Fixes #5060
> Fix the embedded field in nested forms

- src/Form/EmbeddedForm.php
- src/Form/Field.php
- src/Form/Field/Embeds.php
- src/Form/Field/HasMany.php
- src/Form/Field/Table.php
- src/Form/NestedForm.php
修复数据表单的table和embeds功能 可能是该bug的 #3512
> 【重要】修复数据表单的table和embeds功能

- resources/views/form/hasmanytab.blade.php
- src/Form/Field/HasMany.php
> 修复hasMany的tab样式和JS错误

- src/Assets.php
通过ASSET_URL 环境变量可以方便使用cdn回源方式加载静态资源。这里直接使用相对路径导致requirejs只会从当前域名加载文件。或者可以考虑直接写成配置项。
> use admin_assets

- src/Auth/Database/AdminTablesSeeder.php
- src/Console/CreateUserCommand.php
- src/Console/ResetPasswordCommand.php
- src/Controllers/AuthController.php
- src/Controllers/UserController.php
> 修复当修改默认Hash Driver后，修改和新增用户密码不能登陆问题

- src/Auth/Database/OperationLog.php
Update OperationLog.php.
For log model configurable.
> Update OperationLog.php, for log model configurable.

- src/Grid/Column/InputFilter.php
- src/Grid/Column/RangeFilter.php
> fix: 修正列选择器中 InputFilter 和 RangeFilter 的 Reset 按钮重复的问题，将无效的 Reset 删除

- src/Grid/Displayers/ProgressBar.php
Fixes full width error for 100% progress.
> Removed right padding

- src/Actions/Interactor/Form.php
> Prevent double submission

- CONTRIBUTING.md
I found the 404 error link on CONTRIBUTING.md.
> Replace 404 link on CONTRIBUTING.md

- src/Form/Builder.php
> Fix PHPDoc

- src/Actions/BatchAction.php
this pull request implements a feature into BatchAction
* one can add a css class to the button (a href) for styling
* one can add multiple css classes to the button
> feature: add cssClasses to custom batch action button

- src/Middleware/LogOperation.php
#4913 broke trusted proxies setting and introduced a security issue.
https://github.com/z-song/laravel-admin/pull/4913#issuecomment-909292852
> Revert #4913 "解决有时获取IP不正确问题。"

- src/Grid/Selectable.php
I found the return type is wrong during static analysis. Could you please merge it?
> [PHPDoc] fix the return type

- src/Traits/HasAssets.php
Put user CSS after default CSS to user be able to override defaults one easily
> Put user CSS after default CSS to override them

- src/Grid/Model.php
> 修正Grid無法對關聯欄位使用sortable()的問題

- src/Table/Column/ExtendDisplay.php
> replace close-icon to times-icon

- src/Show/Field.php
Add number to show field as number
`$show->field('price')->number()`
Show `100000` as `100,000`
> Show field as number

- resources/views/filter/between.blade.php
- resources/views/filter/betweenDatetime.blade.php
- src/Admin.php
There is no enough width for my screen When I use $filter->column(1 / 3);
> optimization

- src/Form/Field/UploadField.php
- Update UploadField.php to support Laravel 9 since Laravel 9 using Flysystem v3 and the location of file cannot be empty
> Fix Upload File

- src/AdminServiceProvider.php
> [Fix] 修复未引用Str类导致在Laravel5.5 LTS版本中报错的问题

- src/Tree/Tools.php
> [Fixed] fix typo
